services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  setupqueues:
    image: setupqueues
    build:
      context: .
      dockerfile: SetupQueues/Dockerfile
  
  locationservice:
    image: locationservice
    restart: always
    build:
      context: .
      dockerfile: LocationService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      setupqueues:
        condition: service_completed_successfully

  driverservice:
    image: driverservice
    restart: always
    build:
      context: .
      dockerfile: DriverService/Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      setupqueues:
        condition: service_completed_successfully

  logservice:
    image: logservice
    restart: always
    build:
      context: .
      dockerfile: LogService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      setupqueues:
        condition: service_completed_successfully

  passengerservice:
    image: passengerservice
    restart: always
    build:
      context: .
      dockerfile: PassengerService/Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      setupqueues:
        condition: service_completed_successfully

  paymentservice:
    image: paymentservice
    restart: always
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      setupqueues:
        condition: service_completed_successfully

  simulator:
    image: simulator
    build:
      context: .
      dockerfile: Simulator/Dockerfile
    restart: always
    ports:
      - "8000:8080"

volumes: 
    rabbitmq_data:
  
  

  
