services:
  locationservice:
    image: locationservice
    build:
      context: .
      dockerfile: LocationService/Dockerfile
    depends_on:
      - rabbitmq

  driverservice:
    image: driverservice
    build:
      context: .
      dockerfile: DriverService/Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      - rabbitmq

  logservice:
    image: logservice
    build:
      context: .
      dockerfile: LogService/Dockerfile
    depends_on:
      - rabbitmq

  passengerservice:
    image: passengerservice
    build:
      context: .
      dockerfile: PassengerService/Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - rabbitmq

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  setupqueues:
    image: setupqueues
    build:
      context: .
      dockerfile: SetupQueues/Dockerfile

  simulator:
    image: simulator
    build:
      context: .
      dockerfile: Simulator/Dockerfile
    restart: always
    ports:
      - "8000:8080"

volumes: 
    rabbitmq_data:
  
  

  
